//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupName
    {
        public GroupName()
        {
            this.PhoneBooks = new HashSet<PhoneBook>();
        }
    
        public int GroupNameId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PhoneBook> PhoneBooks { get; set; }
    }
}
